# Generated by Django 2.2.24 on 2022-07-18 12:30

from django.db import migrations
from itertools import chain


def is_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats_iterator = Flat.objects.all().iterator()
    try:
        first_iterration = next(flats_iterator)
    except StopIteration:
        pass
    else:
        for flat in chain([first_iterration], flats_iterator):
            flat.new_building = flat.construction_year >= 2015
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(is_new_building)
    ]

