# Generated by Django 2.2.24 on 2022-07-18 13:38

from django.db import migrations
import phonenumbers


def clear_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(phone_number):
            cleared_phone_number = phonenumbers.format_number(
                phone_number, phonenumbers.PhoneNumberFormat.INTERNATIONAL
            )
            flat.owner_pure_phone = cleared_phone_number
            flat.save()
        else:
            flat.owner_pure_phone = None
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20220718_1630'),
    ]

    operations = [
        migrations.RunPython(clear_phone_number)
    ]
