# Generated by Django 2.2.24 on 2022-07-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20220720_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_flats',
            new_name='flats',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_fullname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
